export const CouponCodeActionType = {
    GET_COUPON_CODE: "GET_COUPON_CODE",
    GET_COUPON_CODE_PENDING: "GET_COUPON_CODE_PENDING",
    GET_COUPON_CODE_FULFILLED: "GET_COUPON_CODE_FULFILLED",


    ADD_COUPON_CODE: "ADD_COUPON_CODE",
    ADD_COUPON_CODE_PENDING: "ADD_COUPON_CODE_PENDING",
    ADD_COUPON_CODE_FULFILLED: "ADD_COUPON_CODE_FULFILLED",
    
    TOGGLE_COUPON_CODE: "TOGGLE_COUPON_CODE",
    TOGGLE_COUPON_CODE_PENDING: "TOGGLE_COUPON_CODE_PENDING",
    TOGGLE_COUPON_CODE_FULFILLED: "TOGGLE_COUPON_CODE_FULFILLED",
  };