export const DashboardActionTypes = {
    GET_SUMMERY: "GET_SUMMERY",
    GET_SUMMERY_PENDING: "GET_SUMMERY_PENDING",
    GET_SUMMERY_FULFILLED: "GET_SUMMERY_FULFILLED",

    PLAYED_ANALYTICS: "PLAYED_ANALYTICS",
    PLAYED_ANALYTICS_PENDING: "PLAYED_ANALYTICS_PENDING",
    PLAYED_ANALYTICS_FULFILLED: "PLAYED_ANALYTICS_FULFILLED",

    FAVOURITES_ANALYTICS: "FAVOURITES_ANALYTICS",
    FAVOURITES_ANALYTICS_PENDING: "FAVOURITES_ANALYTICS_PENDING",
    FAVOURITES_ANALYTICS_FULFILLED: "FAVOURITES_ANALYTICS_FULFILLED",

    DOWNLOAD_ANALYTICS: "DOWNLOAD_ANALYTICS",
    DOWNLOAD_ANALYTICS_PENDING: "DOWNLOAD_ANALYTICS_PENDING",
    DOWNLOAD_ANALYTICS_FULFILLED: "DOWNLOAD_ANALYTICS_FULFILLED",

    USER_ANALYTICS: "USER_ANALYTICS",
    USER_ANALYTICS_PENDING: "USER_ANALYTICS_PENDING",
    USER_ANALYTICS_FULFILLED: "USER_ANALYTICS_FULFILLED",


};

