export const UserActionTypes = {

    GET_USER_LIST: "GET_USER_LIST",
    GET_USER_LIST_PENDING: "GET_USER_LIST_PENDING",
    GET_USER_LIST_FULFILLED: "GET_USER_LIST_FULFILLED",

    ADD_USER: "ADD_USER",
    FILTER_USERS_FULFILLED: "FILTER_USERS_FULFILLED",

    UPDATE_LIFE_TIME: "UPDATE_LIFE_TIME",
    UPDATE_LIFE_TIME_FULFILLED: "UPDATE_LIFE_TIME_FULFILLED",

    RESEND_PASSWORD: "RESEND_PASSWORD",
    RESEND_PASSWORD_FULFILLED: "RESEND_PASSWORD_FULFILLED",

    DELETE_USER: "DELETE_USER",
    DELETE_USER_FULFILLED: "DELETE_USER_FULFILLED"
};