export const HarmonyActionTypes = {

  GET_HARMONY_LIST: "GET_HARMONY_LIST",
  GET_HARMONY_LIST_PENDING: "GET_HARMONY_LIST_PENDING",
  GET_HARMONY_LIST_FULFILLED: "GET_HARMONY_LIST_FULFILLED",

  GET_HARMONY: "GET_HARMONY",
  GET_HARMONY_PENDING: "GET_HARMONY_PENDING",
  GET_HARMONY_FULFILLED: "GET_HARMONY_FULFILLED",

  UPDATE_HARMONY: "UPDATE_HARMONY",
  UPDATE_HARMONY_PENDING: "UPDATE_HARMONY_PENDING",
  UPDATE_HARMONY_FULFILLED: "UPDATE_HARMONY_FULFILLED",

  FEATURED_HARMONY: "FEATURED_HARMONY",
  FEATURED_HARMONY_PENDING: "FEATURED_HARMONY_PENDING",
  FEATURED_HARMONY_FULFILLED: "FEATURED_HARMONY_FULFILLED",

  DELETE_HARMONY: "DELETE_HARMONY",
  DELETE_HARMONY_PENDING: "DELETE_HARMONY_PENDING",
  DELETE_HARMONY_FULFILLED: "DELETE_HARMONY_FULFILLED",


    CREATE_HARMONY: "CREATE_HARMONY",
    CREATE_HARMONY_PENDING: "CREATE_HARMONY_PENDING",
    CREATE_HARMONY_FULFILLED: "CREATE_HARMONY_FULFILLED",

  CONFIG_Harmony: "CONFIG_Harmony",
  CONFIG_Harmony_PENDING: "CONFIG_Harmony_PENDING",
  CONFIG_Harmony_FULFILLED: "CONFIG_Harmony_FULFILLED",

  FILTER_POSTS_FULFILLED: "FILTER_POSTS_FULFILLED"
};